// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// RollbackFunc is an autogenerated mock type for the RollbackFunc type
type RollbackFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: tx
func (_m *RollbackFunc) Execute(tx *sql.Tx) {
	_m.Called(tx)
}

type mockConstructorTestingTNewRollbackFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewRollbackFunc creates a new instance of RollbackFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRollbackFunc(t mockConstructorTestingTNewRollbackFunc) *RollbackFunc {
	mock := &RollbackFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
